import type { Conversation,Protocol } from '../types'

const esc=(value?:string)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))
const checked=(active:boolean)=>`<span class="check">${active?'✓':''}</span>`
const lines=(value?:string,count=5)=>`<div class="lined" style="--lines:${count}">${value?`<div class="written">${esc(value).replace(/\n/g,'<br>')}</div>`:''}</div>`

export function printConversationProtocol(conversation:Conversation,protocol:Protocol){
  const kind=protocol.conversationKind??conversation.type??''
  const frame=document.createElement('iframe');frame.style.position='fixed';frame.style.width='0';frame.style.height='0';frame.style.border='0';frame.style.opacity='0';document.body.appendChild(frame)
  const doc=frame.contentDocument;if(!doc){frame.remove();return}
  doc.open();doc.write(`<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Gesprächsprotokoll</title><style>
  @page{size:A4;margin:10mm 11mm 15mm}*{box-sizing:border-box}html{counter-reset:page}body{font-family:Arial,sans-serif;color:#111;margin:0;font-size:10pt}.title{border:1.5px solid #222;background:#e5e5e5;text-align:center;font-size:16pt;padding:4px;margin-bottom:5mm}.grid{display:grid;border-left:1.5px solid #222;border-top:1.5px solid #222;break-inside:avoid}.grid.three{grid-template-columns:1fr 1fr 1fr}.grid.two{grid-template-columns:2fr 1fr}.cell{min-height:8mm;border-right:1.5px solid #222;border-bottom:1.5px solid #222;padding:4px}.label{font-weight:700;margin-right:5px}.types{display:grid;grid-template-columns:1fr 1fr;border:1.5px solid #222;margin:4mm 0;break-inside:avoid}.type{padding:4px;border-right:1.5px solid #222;border-bottom:1.5px solid #222}.type:nth-child(2n){border-right:0}.type:nth-last-child(-n+2){border-bottom:0}.check{display:inline-grid;place-items:center;width:5mm;height:5mm;border:1.5px solid #222;margin-right:5px;font-weight:bold}.section{margin-top:4mm}.section-title{display:inline-block;border:1.5px solid #222;border-bottom:0;min-width:62mm;text-align:center;font-weight:700;padding:3px}.lined{position:relative;border:1.5px solid #222;min-height:calc(var(--lines) * 7mm);background:repeating-linear-gradient(to bottom,transparent 0,transparent calc(7mm - 1px),#777 calc(7mm - 1px),#777 7mm);padding:4px}.written{position:relative;z-index:1;line-height:7mm;white-space:normal}.closing{break-inside:avoid}.signatures{margin-top:4mm;break-inside:avoid}.signature-title{display:inline-block;border:1.5px solid #222;border-bottom:0;padding:3px 18px;font-weight:700}.signature-lines{display:grid;grid-template-columns:1fr 1fr;gap:12mm;border-top:1.5px solid #222;padding-top:11mm}.signature-lines div{border-top:1px solid #222;text-align:center;padding-top:2px;font-size:8pt}.subject{font-size:8pt;color:#444;margin:2mm 0 0}.page-number{position:fixed;bottom:-10mm;left:0;right:0;text-align:center;font-size:8pt;color:#555}.page-number:after{counter-increment:page;content:'Seite ' counter(page)}@media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
  </style></head><body><div class="page-number"></div><div class="title">Gesprächsprotokoll</div><div class="grid three"><div class="cell"><span class="label">Datum:</span>${esc(conversation.date)}</div><div class="cell"><span class="label">Uhrzeit:</span>${esc(protocol.time)}</div><div class="cell"><span class="label">Schuljahr:</span>${esc(protocol.schoolYear)}</div></div><div class="grid two"><div class="cell"><span class="label">Name/Mitarbeit:</span>${esc(protocol.childName)}</div><div class="cell"><span class="label">Klasse:</span>${esc(protocol.className)}</div></div><div class="subject"><b>Anlass:</b> ${esc(conversation.subject)}</div><div class="types"><div class="type">${checked(kind==='Elterngespräch')} Elterngespräch</div><div class="type">${checked(kind==='Telefonat')} Telefonat</div><div class="type">${checked(kind==='Schülergespräch')} Schülergespräch</div><div class="type">${checked(kind==='Mitarbeitergespräch')} Mitarbeitergespräch</div></div><div class="section"><div class="section-title">Teilnehmer:</div>${lines(protocol.participants,2)}</div><div class="section"><div class="section-title">Inhalte:</div>${lines([protocol.occasion,protocol.course,protocol.statements].filter(Boolean).join('\n\n'),8)}</div><div class="closing"><div class="section"><div class="section-title">Ergebnisse/Vereinbarungen:</div>${lines([protocol.agreements,protocol.tasks&&`Aufgaben: ${protocol.tasks}`,protocol.responsible&&`Verantwortlich: ${protocol.responsible}`,protocol.deadlines&&`Frist: ${protocol.deadlines}`].filter(Boolean).join('\n'),4)}</div><div class="signatures"><div class="signature-title">Unterschriften:</div><div class="signature-lines"><div>Gesprächsführung</div><div>Gesprächsteilnehmer/in</div></div></div></div></body></html>`);doc.close()
  let printed=false;const print=()=>{if(printed||!frame.isConnected)return;printed=true;frame.contentWindow?.focus();frame.contentWindow?.print();setTimeout(()=>frame.remove(),1000)};frame.onload=print;setTimeout(print,300)
}
