import { createBackup,restoreBackup } from './backup'

type Writable={write:(data:string)=>Promise<void>;close:()=>Promise<void>}
export type SyncHandle={name:string;getFile:()=>Promise<File>;createWritable:()=>Promise<Writable>;queryPermission?:(o:{mode:'readwrite'})=>Promise<PermissionState>;requestPermission?:(o:{mode:'readwrite'})=>Promise<PermissionState>}
const DB='schoolPlannerFileSync',STORE='handles',KEY='unified-backup'
function handleDB(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function saveHandle(handle:SyncHandle){const database=await handleDB();await new Promise<void>((resolve,reject)=>{const tx=database.transaction(STORE,'readwrite');tx.objectStore(STORE).put(handle,KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function getSyncHandle(){const database=await handleDB();return new Promise<SyncHandle|undefined>((resolve,reject)=>{const request=database.transaction(STORE).objectStore(STORE).get(KEY);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function clearSyncHandle(){const database=await handleDB();await new Promise<void>((resolve,reject)=>{const tx=database.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function ensurePermission(handle:SyncHandle){if(!handle.queryPermission)return true;if(await handle.queryPermission({mode:'readwrite'})==='granted')return true;return await handle.requestPermission?.({mode:'readwrite'})==='granted'}
export function fileSyncSupported(){return typeof (window as any).showOpenFilePicker==='function'&&typeof (window as any).showSaveFilePicker==='function'}
export async function connectExistingSyncFile(){const picker=(window as any).showOpenFilePicker as (o:unknown)=>Promise<SyncHandle[]>;const[handle]=await picker({types:[{description:'Schulplaner-Synchronisierung',accept:{'application/json':['.json']}}],multiple:false});if(!await ensurePermission(handle))throw new Error('permission');await saveHandle(handle);return handle}
export async function createNewSyncFile(){const picker=(window as any).showSaveFilePicker as (o:unknown)=>Promise<SyncHandle>;const handle=await picker({suggestedName:'schulplaner-sync.json',types:[{description:'Schulplaner-Synchronisierung',accept:{'application/json':['.json']}}]});await saveHandle(handle);await writeSyncFile(handle);return handle}
export async function writeSyncFile(handle?:SyncHandle){const target=handle??await getSyncHandle();if(!target||!await ensurePermission(target))throw new Error('permission');const writable=await target.createWritable();await writable.write(JSON.stringify(await createBackup(),null,2));await writable.close();localStorage.setItem('schoolPlannerSyncLast',new Date().toISOString());return target.name}
export async function readSyncFile(handle?:SyncHandle){const target=handle??await getSyncHandle();if(!target||!await ensurePermission(target))throw new Error('permission');const file=await target.getFile(),data=JSON.parse(await file.text());await restoreBackup(data,true);localStorage.setItem('schoolPlannerSyncLast',new Date().toISOString());return target.name}
let syncTimer:number|undefined
export function scheduleSyncWrite(){window.clearTimeout(syncTimer);syncTimer=window.setTimeout(()=>{getSyncHandle().then(handle=>handle&&writeSyncFile(handle)).catch(()=>undefined)},1200)}
