import { useEffect,useRef,useState } from 'react'
import { CalendarSync,Cloud,Database,Download,Eye,EyeOff,FilePlus2,FolderOpen,RefreshCw,ShieldCheck,Unplug,Upload,WifiOff } from 'lucide-react'
import { downloadBackup,restoreBackup } from '../services/backup'
import { clearSyncHandle,connectExistingSyncFile,createNewSyncFile,fileSyncSupported,getSyncHandle,readSyncFile,writeSyncFile } from '../services/fileSync'
import { calDavAvailable,calDavStatus,disconnectCalDav,saveCalDav,syncCalDav,type CalDavStatus } from '../services/caldav'

function CalDavSettings(){
  const [status,setStatus]=useState<CalDavStatus>({configured:false}),[url,setUrl]=useState('https://aloberlin.de/caldav/thomas.schofer/home'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{calDavStatus().then(value=>{setStatus(value);if(value.url)setUrl(value.url);if(value.username)setUsername(value.username)}).catch(()=>undefined)},[])
  async function connect(){setBusy(true);setMessage('Verbindung wird geprüft …');try{const result=await saveCalDav(url,username,password);setPassword('');setStatus({configured:true,url,username,lastSync:result.lastSync});setMessage(`${result.events.length} Termine wurden synchronisiert.`)}catch(error){setMessage(error instanceof Error?error.message:'Der Kalender konnte nicht verbunden werden.')}finally{setBusy(false)}}
  async function refresh(){setBusy(true);setMessage('Kalender wird aktualisiert …');try{const result=await syncCalDav();if(result){setStatus(value=>({...value,lastSync:result.lastSync}));setMessage(`${result.events.length} Termine wurden aktualisiert.`)}}catch(error){setMessage(error instanceof Error?error.message:'Die Aktualisierung ist fehlgeschlagen.')}finally{setBusy(false)}}
  async function disconnect(){if(!confirm('Kalender-Abo trennen und die übernommenen Termine entfernen?'))return;await disconnectCalDav();setStatus({configured:false});setMessage('Kalender-Abo wurde getrennt.');setPassword('')}
  const last=status.lastSync?new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short'}).format(new Date(status.lastSync)):''
  return <section className="settings-card caldav-card"><CalendarSync/><div><h3>CalDAV-Kalender abonnieren</h3><p>Termine aus einem externen Kalender werden nur lesbar übernommen und beim Start sowie alle 30 Minuten aktualisiert.</p>{!calDavAvailable()?<p className="notice">CalDAV ist in der installierten Mac-App verfügbar.</p>:status.configured?<><div className="sync-status connected"><span/><div><b>Verbunden</b><small>{status.username} · {status.url}</small>{last&&<small>Letzter Abgleich: {last}</small>}</div></div><div className="sync-actions"><button className="primary" disabled={busy} onClick={()=>void refresh()}><RefreshCw/> {busy?'Wird aktualisiert …':'Jetzt synchronisieren'}</button><button className="ghost danger" disabled={busy} onClick={()=>void disconnect()}><Unplug/> Abo trennen</button></div></>:<div className="caldav-fields"><label>CalDAV-Adresse<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Benutzername<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Kennwort<span className="password-field"><input type={showPassword?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="icon-btn" aria-label={showPassword?'Kennwort verbergen':'Kennwort anzeigen'} onClick={()=>setShowPassword(value=>!value)}>{showPassword?<EyeOff/>:<Eye/>}</button></span></label><button className="primary" disabled={busy||!url||!username||!password} onClick={()=>void connect()}><CalendarSync/> {busy?'Verbindung wird geprüft …':'Verbinden und synchronisieren'}</button></div>}{message&&<p className="notice">{message}</p>}</div></section>
}

export function Settings(){
  const input=useRef<HTMLInputElement>(null),[message,setMessage]=useState(''),[syncName,setSyncName]=useState(''),[syncMessage,setSyncMessage]=useState(''),supported=fileSyncSupported()
  useEffect(()=>{getSyncHandle().then(handle=>setSyncName(handle?.name??'')).catch(()=>undefined)},[])
  async function exportFile(){try{const mode=await downloadBackup();setMessage(mode==='chosen'?'Gesamt-Backup am ausgewählten Speicherort gespeichert.':'Gesamt-Backup wurde heruntergeladen.')}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;setMessage('Das Backup konnte nicht gespeichert werden.')}}
  async function importFile(file?:File){if(!file)return;try{const raw=JSON.parse(await file.text());if(!confirm('Das Gesamt-Backup ersetzt die vorhandenen lokalen Daten. Fortfahren?'))return;await restoreBackup(raw,true);setMessage('Gesamt-Backup erfolgreich wiederhergestellt. Bitte laden Sie die App neu.')}catch{setMessage('Die Datei ist kein gültiges Schulplaner-Backup.')}}
  async function connect(){try{const handle=await connectExistingSyncFile();setSyncName(handle.name);if(confirm('Sync-Datei verbunden. Sollen deren Daten jetzt in die App geladen werden?'))await readSyncFile(handle);setSyncMessage('Sync-Datei erfolgreich verbunden.')}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;setSyncMessage('Die Sync-Datei konnte nicht verbunden werden.')}}
  async function create(){try{const handle=await createNewSyncFile();setSyncName(handle.name);setSyncMessage('Neue Sync-Datei angelegt und mit allen App-Daten befüllt.')}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;setSyncMessage('Die Sync-Datei konnte nicht angelegt werden.')}}
  async function push(){try{await writeSyncFile();setSyncMessage('Alle Daten wurden in die Sync-Datei geschrieben.')}catch{setSyncMessage('Kein Zugriff auf die Sync-Datei. Bitte erneut verbinden.')}}
  async function pull(){if(!confirm('Lokale Daten durch den Stand der Sync-Datei ersetzen?'))return;try{await readSyncFile();setSyncMessage('Daten aus der Sync-Datei geladen. Bitte laden Sie die App neu.')}catch{setSyncMessage('Die Sync-Datei konnte nicht gelesen werden.')}}
  async function disconnect(){if(!confirm('Verbindung zur Sync-Datei trennen? Ihre lokalen Daten bleiben erhalten.'))return;await clearSyncHandle();setSyncName('');setSyncMessage('Verbindung getrennt.')}
  return <><div className="section-heading"><div><p>KONFIGURATION</p><h2>Einstellungen</h2></div></div><div className="settings-grid">
    <CalDavSettings/>
    <section className="settings-card sync-card"><Cloud/><div><h3>Datei-Synchronisierung</h3><p>Eine gemeinsame Sicherungsdatei für die gesamte App: Schulleitungsplanung, Unterrichtsplanung, Klassen, Noten, Kompetenzraster und Listen. Die Datei kann in einem lokalen iCloud-Drive-, OneDrive- oder Dropbox-Ordner liegen.</p>{!supported?<div className="sync-fallback"><b>Direkte Dateiverknüpfung wird von diesem Browser nicht unterstützt.</b><span>Verwenden Sie unten Gesamt-Backup exportieren/importieren oder öffnen Sie die App in Chrome beziehungsweise Edge.</span></div>:syncName?<><div className="sync-status connected"><span/> <div><b>Verbunden</b><small>{syncName}</small></div></div><div className="sync-actions"><button className="primary" onClick={push}><Upload/> Jetzt sichern</button><button className="ghost" onClick={pull}><RefreshCw/> Stand laden</button><button className="ghost danger" onClick={disconnect}><Unplug/> Trennen</button></div></>:<><div className="sync-status"><span/> <b>Nicht verbunden</b></div><div className="sync-actions"><button className="primary" onClick={connect}><FolderOpen/> Vorhandene Sync-Datei verbinden</button><button className="ghost" onClick={create}><FilePlus2/> Neue Sync-Datei anlegen</button></div></>}{syncMessage&&<p className="notice">{syncMessage}</p>}</div></section>
    <section className="settings-card"><Database/><div><h3>Manuelles Gesamt-Backup</h3><p>Zusätzliche Sicherheitskopie aller App- und Unterrichtsdaten. Export und Wiederherstellung verwenden dasselbe gemeinsame Format.</p><div><button className="primary" onClick={exportFile}><Download/> Gesamt-Backup speichern</button><button className="ghost" onClick={()=>input.current?.click()}><Upload/> Gesamt-Backup laden</button><input ref={input} hidden type="file" accept="application/json" onChange={e=>importFile(e.target.files?.[0])}/></div>{message&&<p className="notice">{message}</p>}</div></section>
    <section className="settings-card"><ShieldCheck/><div><h3>Datenschutz</h3><p>Alle Daten bleiben lokal. Es gibt keine Serverübertragung, keine öffentliche Cloud-Datenbank, kein Tracking und keine Telemetrie.</p></div></section>
    <section className="settings-card"><WifiOff/><div><h3>Offline verfügbar</h3><p>Die App funktioniert nach dem ersten Laden vollständig ohne Internetverbindung.</p></div></section>
  </div></>
}
