import { useEffect,useState } from 'react'
import { NavLink,Outlet,useLocation,useNavigate } from 'react-router-dom'
import { Archive,BookOpen,BookOpenCheck,CalendarDays,CheckSquare2,Columns3,ContactRound,LayoutDashboard,Mail,Menu,MessagesSquare,Plus,RefreshCw,Search,Settings,Sun,UsersRound,X } from 'lucide-react'
import { QuickCreate } from '../features/quick-create/QuickCreate'
const links=[['/','Dashboard',LayoutDashboard],['/heute','Heute',Sun],['/email-assistent','E-Mail-Assistent',Mail],['/kalender','Kalender',CalendarDays],['/aufgaben','Aufgaben',CheckSquare2],['/wochenplanung','Wochenplanung',Columns3],['/unterrichtsplaner','Unterrichtsplaner',BookOpenCheck],['/gespraeche','Gespräche',MessagesSquare],['/konferenzen','Konferenzen',UsersRound],['/wiedervorlage','Wiedervorlage',RefreshCw],['/personen','Personen',ContactRound],['/dokumentation','Dokumentation',BookOpen],['/archiv','Archiv',Archive],['/einstellungen','Einstellungen',Settings]] as const
const teachingTabs=[['uebersicht','Übersicht'],['aufgaben','Aufgaben'],['stoff','Unterrichtsplanung'],['stoffuebersicht','Stoffverteilung'],['klassen','Klassen & Schüler'],['noten','Noten'],['kompetenz','Kompetenzraster'],['kann','Kann-Listen'],['klassenlisten','Klassenlisten']] as const
function schoolYear(){const fallback={bezeichnung:'2026/27',von:'2026-08-24',bis:'2027-06-30'};try{const data=JSON.parse(localStorage.getItem('schulplaner_v1')??'{}'),today=new Date().toISOString().slice(0,10),years=(data.schuljahre??[]) as {bezeichnung:string;von:string;bis:string}[];return years.find(y=>today>=y.von&&today<=y.bis)??years.find(y=>y.von>today)??years.at(-1)??fallback}catch{return fallback}}
export function Shell(){
  const[quick,setQuick]=useState(false),[menu,setMenu]=useState(false),[year,setYear]=useState(schoolYear())
  const nav=useNavigate(),loc=useLocation(),isTeaching=loc.pathname.startsWith('/unterrichtsplaner'),selectedTab=new URLSearchParams(loc.search).get('tab')??'uebersicht'
  const current=links.find(([p])=>p==='/'?loc.pathname==='/':loc.pathname.startsWith(p))?.[1]??'Schulplaner'
  useEffect(()=>{const update=()=>setYear(schoolYear());const timer=window.setInterval(update,1500);window.addEventListener('storage',update);window.addEventListener('focus',update);return()=>{window.clearInterval(timer);window.removeEventListener('storage',update);window.removeEventListener('focus',update)}},[])
  return <div className="app-shell"><aside className={menu?'open':''}><div className="brand"><span>SP</span><div><strong>Schulplaner</strong><small>Schulleitung</small></div><button onClick={()=>setMenu(false)} aria-label="Menü schließen"><X/></button></div><nav>{links.map(([path,label,Icon])=><div className="nav-entry" key={path}><NavLink to={path} end={path==='/' } onClick={()=>path!=='/unterrichtsplaner'&&setMenu(false)}><Icon/>{label}</NavLink>{path==='/unterrichtsplaner'&&isTeaching&&<div className="teaching-submenu">{teachingTabs.map(([tab,label])=><NavLink key={tab} to={`/unterrichtsplaner?tab=${tab}`} className={selectedTab===tab?'active':''} onClick={()=>setMenu(false)}>{label}</NavLink>)}</div>}</div>)}</nav><div className="privacy">● Daten bleiben lokal</div></aside><main><header className={isTeaching?'topbar teaching-topbar':'topbar'}><button className="menu-btn" onClick={()=>setMenu(true)} aria-label="Menü öffnen"><Menu/></button><div className="topbar-title"><small>Übersicht</small><h1>{current}</h1></div><div className="top-actions">{isTeaching&&year&&<span className="top-schoolyear">Schuljahr {year.bezeichnung} · {new Date(year.von+'T00:00').toLocaleDateString('de-DE')} – {new Date(year.bis+'T00:00').toLocaleDateString('de-DE')}</span>}<button className="search-btn" onClick={()=>nav('/suche')}><Search/> <span>Suchen</span></button><button className="primary" onClick={()=>setQuick(true)}><Plus/> Neu</button></div></header><div className="page"><Outlet/></div></main><nav className="bottom-nav"><NavLink to="/heute"><Sun/>Heute</NavLink><NavLink to="/aufgaben"><CheckSquare2/>Aufgaben</NavLink><button onClick={()=>setQuick(true)} aria-label="Neu erstellen"><Plus/></button><NavLink to="/kalender"><CalendarDays/>Kalender</NavLink><button onClick={()=>setMenu(true)}><Menu/>Mehr</button></nav>{quick&&<QuickCreate onClose={()=>setQuick(false)}/>}</div>
}
